### ISSUE TITLE
Need an equivalent of KOREBUILD_SKIP_RUNTIME_INSTALL which prevents installing shared runtimes

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KoreBuild#209] opened 2017-03-22 20:47 UTC
We need this to avoid installing shared runtimes while building Universe in parallel

**Comment by mikeharder** [comment] 2017-04-03 21:52
Build failure caused by this:

http://aspnetci/viewLog.html?buildId=195760&buildTypeId=Lite_UniverseTest&tab=buildResultsDiv

**Comment by mikeharder** [comment] 2017-04-04 00:57
Another failure: http://aspnetci/viewLog.html?buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&buildId=195750

**Comment by mikeharder** [comment] 2017-04-07 01:24
Another failure: http://aspnetci/viewLog.html?buildId=197361&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

**Comment by kichalla** [comment] 2017-04-07 15:39
Fixed with https://github.com/aspnet/KoreBuild/commit/aa53be86c5c3e0a2d3e6be62af4f0c5e1b5b067e

**Closed as completed** 2017-04-21 20:51 UTC
Labels: bug, 3 - Done
