### ISSUE TITLE
Install 2.0.0-beta-* runtime

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#190] opened 2017-03-03 19:52 UTC
KoreBuild should start installing the 2.0.0-beta-* runtime (which matches the current version on the MyGet feed).  This should be sufficient to start moving repos to 2.0.  We want to move Benchmarks to 2.0 ASAP.

CC: @davidfowl

**Comment by natemcmaster** [comment] 2017-03-03 20:21
Duplicate of https://github.com/aspnet/Coherence/issues/166. We're working on it.

**Closed as completed by natemcmaster** 2017-03-03 20:21 UTC
